version: '3'

volumes:
  db:
    driver: local
  email:
    driver: local

services:
  web:
    build: "./docker/web"
    depends_on:
      - server
      - client
    container_name: "grabook_web"
    ports:
      - 80:80
    volumes:
      - ./src/server:/var/www/html:cached
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:cached

  db:
    image: mariadb:10.5
    container_name: "grabook_db"
    restart: always
    environment:
      MYSQL_DATABASE: grabook
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - 33061:3306
    volumes:
      - db:/var/lib/mysql:cached
      - "./docker/db/init:/docker-entrypoint-initdb.d:cached"

  email:
    image: mailhog/mailhog
    container_name: grabook_email
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - "email:/tmp"
